---
# requires:
#  test-kitchen
#  kitchen-vagrant
#  kitchen-ansiblepush
#  kitchen-inspec

driver:
  name: vagrant
  gui: false

platforms:
  - name: win2012r2
    driver_config:
      box: ## YOUR WINDOWS VAGRANT BOX NAME ###
      box_url: ## YOUR VAGRANT BOX DOWNLOAD URL HERE ###
      box_download_insecure: true
      communicator: winrm
      username: packer
      password: packer
      network:
        - ["forwarded_port", {guest: 5986, host: 55986}]
      port: 55986
      customize:
        cpus: 2
        memory: 4096
      provision: false

transport:
  name: winrm
  winrm_transport: negotiate

provisioner:
  name: ansible_push
  ansible_config: test/ansible.cfg
  verbose: vvv
  mygroup: kitchen-windows
  diff: true
  host_key_checking: false
  ansible_connection: winrm
  ansible_port: 55986
  generate_inv: true
  use_instance_name: false
  chef_bootstrap_url: nil

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default/controls/win-test_spec.rb
  format: junit
  output: "%{platform}_%{suite}_inspec.xml"

suites:
  - name: default
    provisioner:
      playbook: test/integration/default/default.yml
